### PR TITLE
(not fully working) Expo 44 integrated with react-native-tvos.

### PR DESCRIPTION
**Pull request by beauner69**
Only works if you limit podfile to ios or tvos targets.

### CODE REVIEW

**Comment by douglowder** [comment]
Interesting... will take a look.

**Comment by douglowder** [comment]
Expo 44 is based on RN 0.64, not 0.66, is there some reason why you need to move to 0.66?

**Comment by beauner69** [comment]
You make a good point. I am updating my project, which is something I only do every 9-12 months because it's often quite the undertaking. As part of this I'm updating the modules and pushing as far as I can.

From what I understand, the Expo modules are separate entities - although with the move away from "unimodules" towards just including the Expo project, this boundary becomes very blurred. In theory they should be OK, but I have no proof of this - other than having personally used unimodules on RN that didn't match expo's RN target at that time.

Now that I have a way to get the project built, I will test the modules later today and let you know if they work as expected.

**Comment by douglowder** [comment]
@beauner69 I will merge this to a branch to make it easier for me to test and add changes as needed.

**Comment by beauner69** [comment]
Thank you!

**Comment by douglowder** [comment]
Ok I've started taking a look at this. My current working theory is that when both iOS and tvOS targets are in the Podfile, the build products are `EXApplication-iOS`, `EXApplication-tvOS`, `EXConstants-iOS`, `EXConstants-tvOS`, etc., but if only one target is present, we just have `EXApplication`, `EXConstants`, etc. -- and this is breaking the Expo script `expo_patch_react_imports!`. Still investigating.

**Pull request merged**
